import {getMessaging,getToken,deleteToken,isSupported,onMessage} from 'firebase/messaging';
import {vapidKey} from './config.js';
import QRCode from 'qrcode';
import {$,account,call,notice,showError,busy,install,signOut,line,clear,button,el,fecha,duracion,popup,credentials} from './common.js';
const {app,auth,ready}=account();let user=null,agents=[],points=[],history=[],nextCursor=null,cursors=[null],page=0,active='rondas',polling=false;
install();
const api=(action,data)=>call(auth,action,data);
function values(form){return Object.fromEntries(new FormData(form));}
function assign(form,data){form.reset();for(const [k,v]of Object.entries(data)){const n=form.elements.namedItem(k);if(n)n.type==='checkbox'?n.checked=!!v:n.value=v??'';}}
function selectOptions(n,items){const selected=n.value;clear(n);n.append(new Option('Todos',''));for(const a of items)n.append(new Option(a.nombre+' · '+a.id,a.id));n.value=selected;}
async function filters(){const result=await api('agentes');agents=result.agentes;selectOptions($('filterAgent'),agents);}
async function loadHistory(reset=false){if(reset){page=0;cursors=[null];}const request={...values($('filters')),archivadas:$('archived').checked,cursor:cursors[page]};const result=await api('rondas',request);history=result.rondas;nextCursor=result.siguiente;clear($('rounds'));for(const r of history)renderRound(r);if(!history.length)$('rounds').append(el('p','No hay rondas con esos filtros.','empty'));$('page').textContent='Página '+(page+1);$('prev').disabled=page===0;$('next').disabled=!nextCursor;$('count').textContent=`${history.length} rondas en esta página`;}
function renderRound(r){const card=el('article','','card'),header=el('div','','row');header.append(el('h3','Ronda '+(r.tipoRonda||'anterior')),el('span',r.estado||'Registro anterior','badge '+(r.estado||'')));card.append(header);line(card,'Agente:',r.agenteNombre||r.nombreAgente||'—');line(card,'Turno:',r.agenteTurno||r.turno);line(card,'Inicio:',fecha(r.inicioTimestamp));line(card,'Duración:',duracion(r.duracionSegundos));line(card,'Puntos:',`${r.totalValidados??'—'} / ${r.ruta?.length??'ruta histórica no disponible'}`);if(r.archivada)line(card,'Archivada:',r.motivoArchivo);
 const actions=el('div','','actions'),detail=el('div','','detail');detail.hidden=true;let loaded=false;
 actions.append(button('Ver detalle',async b=>{if(!loaded){await busy(b,async()=>{const d=await api('detalle',{rondaId:r.id});clear(detail);line(detail,'Cargo:',d.ronda.agenteCargo);if(d.ronda.motivoCancelacion)line(detail,'Motivo:',d.ronda.motivoCancelacion);if(!d.validaciones.length)detail.append(el('p','Sin puntos registrados.'));for(const v of d.validaciones){const row=el('div','','validation');line(row,`${v.orden}. ${v.puntoCodigo}`,v.puntoNombre);line(row,'Registrado:',fecha(v.timestamp));line(row,'Dirección configurada:',v.direccion);if(v.gps)line(row,'GPS aproximado:',`${v.gps.lat}, ${v.gps.lng} · ±${Math.round(v.gps.precision)} m`);if(v.evidenciaId)row.append(button('Ver fotografía',async b=>busy(b,async()=>{const e=await api('evidencia',{evidenciaId:v.evidenciaId});popup('Fotografía del punto',body=>{const img=el('img');img.src='data:'+e.mime+';base64,'+e.base64;img.alt='Evidencia de '+v.puntoNombre;img.className='evidence';body.append(img);});})));else row.append(el('p','Este registro anterior no conserva fotografía en el sistema.','muted'));detail.append(row);}loaded=true;});}
 if(loaded){detail.hidden=!detail.hidden;b.textContent=detail.hidden?'Ver detalle':'Ocultar detalle';}}));
 if(user.rol==='ADMIN'&&!r.archivada){if(r.estado==='EN_CURSO')actions.append(button('Cerrar como incompleta',async b=>{const motivo=prompt('Motivo del cierre administrativo:');if(motivo?.trim())await busy(b,async()=>{await api('cerrar-ronda',{rondaId:r.id,motivo});await loadHistory();});},'danger'));else actions.append(button('Archivar',async b=>{const motivo=prompt('Motivo del archivo (se conserva el historial):');if(motivo?.trim())await busy(b,async()=>{await api('archivar',{rondaId:r.id,motivo});await loadHistory();});},'danger'));}
 card.append(actions,detail);$('rounds').append(card);
}
async function showAgents(){const r=await api('agentes');agents=r.agentes;clear($('agents'));for(const a of agents){const card=el('article','','card');card.append(el('h3',a.id+' · '+a.nombre));line(card,'Cargo:',a.cargo);line(card,'Turno:',a.turno);line(card,'Estado:',a.activo?'Activo':'Deshabilitado');if(user.rol==='ADMIN'){line(card,'Acceso:',a.uid?'Configurado':'Pendiente de configurar');const actions=el('div','','actions');actions.append(button('Editar',()=>{assign($('agentForm'),{codigo:a.id,...a});$('agentForm').elements.codigo.readOnly=true;$('agentForm').scrollIntoView({behavior:'smooth'});}),button(a.activo?'Deshabilitar':'Habilitar',async b=>busy(b,async()=>{await api('guardar-agente',{...a,codigo:a.id,activo:!a.activo});await showAgents();})),button(a.uid?'Renovar contraseña':'Crear acceso',async b=>{if(a.uid&&!confirm('La contraseña anterior dejará de funcionar. ¿Continuar?'))return;await busy(b,async()=>{credentials(await api('credencial-agente',{codigo:a.id}));await showAgents();});}));card.append(actions);}$('agents').append(card);}if(!agents.length)$('agents').append(el('p','No hay agentes registrados.'));}
async function drawQR(canvas,p){const url=location.origin+'/ronda.html?punto='+encodeURIComponent(p.codigo||p.id);await QRCode.toCanvas(canvas,url,{width:320,margin:4,errorCorrectionLevel:'H'});const c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(120,149,80,22);c.fillStyle='#12243a';c.font='bold 10px Arial';c.textAlign='center';c.fillText('PREVENCIÓN',160,164);return canvas;}
function qr(p){popup('QR '+(p.codigo||p.id),body=>{body.append(el('h3',p.nombre));const canvas=el('canvas');body.append(canvas);drawQR(canvas,p).catch(showError);body.append(button('Descargar PNG',()=>{const link=el('a');link.href=canvas.toDataURL('image/png');link.download='QR-'+(p.codigo||p.id)+'.png';link.click();}));});}
async function printAll(){const result=await api('puntos');const list=$('printArea');clear(list);for(const p of result.puntos.filter(p=>p.activo)){const card=el('section','','printCard');card.append(el('h2',p.nombre),el('p',p.codigo+' · '+p.tipoRonda+' · '+p.funcionQR));const canvas=el('canvas');await drawQR(canvas,p);card.append(canvas);list.append(card);}window.print();}
async function showPoints(){const r=await api('puntos');points=r.puntos;clear($('points'));for(const p of points){const card=el('article','','card');card.append(el('h3',p.codigo+' · '+p.nombre));line(card,'Recorrido:',`${p.tipoRonda} · ${p.funcionQR} · Orden ${p.orden}`);line(card,'Dirección:',p.direccion||'Pendiente de configurar');line(card,'Estado:',p.activo?'Activo':'Desactivado');const actions=el('div','','actions');actions.append(button('Ver / descargar QR',()=>qr(p)),button('Editar',()=>{assign($('pointForm'),p);$('pointForm').elements.codigo.readOnly=true;$('pointForm').scrollIntoView({behavior:'smooth'});}));card.append(actions);$('points').append(card);}await checkRoutes();}
async function checkRoutes(){const r=await api('comprobar-rutas');clear($('routeState'));for(const x of r.rutas)$('routeState').append(el('p',x.tipo+': '+(x.ok?'Ruta válida · '+x.total+' puntos':x.error),x.ok?'success':'error'));}
async function showUsers(){const r=await api('usuarios');clear($('users'));for(const u of r.usuarios){const card=el('article','','card');card.append(el('h3',u.correo||u.id));line(card,'Rol:',u.rol);line(card,'Estado:',u.activo?'Activo':'Deshabilitado');card.append(button('Editar permisos',()=>{assign($('userForm'),{uid:u.id,...u});$('userForm').elements.correo.readOnly=true;}));if(u.id!==user.uid)card.append(button('Renovar contraseña',async b=>{if(confirm('¿Invalidar la contraseña anterior?'))await busy(b,async()=>credentials({uid:u.correo,...await api('clave-panel',{uid:u.id})}));}));$('users').append(card);}}
async function showPushStatus(){const r=await api('push-estado');clear($('pushStatus'));for(const e of r.eventos){const row=el('div','','validation');row.append(el('p',`${fecha(e.creadoEn)} · ${e.tipo} · ${e.estado} · ${e.intentos} intentos`));if(['FALLIDO','PENDIENTE'].includes(e.estado))row.append(button('Reintentar',async b=>busy(b,async()=>{await api('push-reintentar',{eventoId:e.id});await showPushStatus();})));$('pushStatus').append(row);}}
async function avisos(){const result=await api('avisos');const key='leidos_'+user.uid;let seen;try{seen=new Set(JSON.parse(localStorage.getItem(key)||'[]'));}catch{seen=new Set();}clear($('notifications'));for(const n of result.avisos){const row=el('div','','validation');row.append(el('strong',`${n.tipo} · ${n.nombre}`),el('p',`${n.ronda} · ${fecha(n.fecha)}`));if(!seen.has(n.id))row.classList.add('unread');$('notifications').append(row);}$('notificationCount').textContent=String(result.avisos.filter(n=>!seen.has(n.id)).length);$('markRead').onclick=()=>{localStorage.setItem(key,JSON.stringify(result.avisos.map(n=>n.id)));avisos().catch(showError);};}
async function section(name){active=name;for(const s of document.querySelectorAll('[data-panel]'))s.hidden=s.dataset.panel!==name;for(const n of document.querySelectorAll('[data-tab]'))n.classList.toggle('selected',n.dataset.tab===name);if(name==='rondas')await loadHistory(true);if(name==='agentes')await showAgents();if(name==='puntos')await showPoints();if(name==='usuarios')await showUsers();if(name==='avisos'){await avisos();if(user.rol==='ADMIN')await showPushStatus();}}
for(const n of document.querySelectorAll('[data-tab]'))n.onclick=()=>section(n.dataset.tab).catch(showError);
$('filters').onsubmit=e=>{e.preventDefault();loadHistory(true).catch(showError);};$('prev').onclick=()=>{if(page>0){page--;loadHistory().catch(showError);}};$('next').onclick=()=>{if(nextCursor){cursors[++page]=nextCursor;loadHistory().catch(showError);}};
$('agentForm').onsubmit=e=>{e.preventDefault();const b=$('saveAgent');busy(b,async()=>{const d=values($('agentForm'));d.activo=$('agentForm').elements.activo.checked;const result=await api('guardar-agente',d);notice(result.aviso||'Agente guardado. Usa Crear acceso para asignar su contraseña.','success');$('agentForm').reset();$('agentForm').elements.codigo.readOnly=false;await showAgents();await filters();});};
$('pointForm').onsubmit=e=>{e.preventDefault();busy($('savePoint'),async()=>{const d=values($('pointForm'));d.activo=$('pointForm').elements.activo.checked;await api('guardar-punto',d);notice('Punto guardado. Las rondas iniciadas conservan su ruta.','success');$('pointForm').reset();$('pointForm').elements.codigo.readOnly=false;await showPoints();});};
$('userForm').onsubmit=e=>{e.preventDefault();busy($('saveUser'),async()=>{const d=values($('userForm'));d.activo=$('userForm').elements.activo.checked;const result=await api('guardar-usuario',d);if(result.password)credentials({uid:d.correo,...result});else notice('Permisos guardados; se conserva la contraseña de la cuenta existente.','success');$('userForm').reset();$('userForm').elements.correo.readOnly=false;await showUsers();});};
for(const [id,field]of [['agentForm','codigo'],['pointForm','codigo'],['userForm','correo']])$(id).addEventListener('reset',()=>$(id).elements[field].readOnly=false);
$('printAll').onclick=()=>busy($('printAll'),printAll);
$('enablePush').onclick=()=>busy($('enablePush'),async()=>{if(!('Notification' in window))throw Error('Este navegador no admite notificaciones.');const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Permiso de notificaciones no concedido.');if(!await isSupported())throw Error('Este navegador no admite push. En iPhone instala la PWA y ábrela desde Inicio.');const registration=await navigator.serviceWorker.ready;const token=await getToken(getMessaging(app),{vapidKey,serviceWorkerRegistration:registration});if(!token)throw Error('No se pudo obtener el token.');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))).map(b=>b.toString(16).padStart(2,'0')).join('');
// Guardar el identificador esperado antes del envío permite revocarlo incluso
// si el servidor registra el dispositivo pero se pierde su respuesta.
localStorage.setItem('push_'+user.uid,user.uid+'_'+hash);await api('push-registrar',{token});notice('Notificaciones activadas para esta cuenta.','success');});
$('logout').onclick=()=>busy($('logout'),async()=>{const deviceId=localStorage.getItem('push_'+user.uid);if(deviceId){await api('push-quitar',{deviceId});localStorage.removeItem('push_'+user.uid);}if(await isSupported())try{await deleteToken(getMessaging(app));}catch{}await signOut(auth);location.replace('/login.html');});
async function poll(){if(polling||document.hidden||!user||!navigator.onLine)return;polling=true;try{await api('push-procesar');await avisos();if(active==='rondas'&&!document.querySelector('.detail:not([hidden])'))await loadHistory();if(active==='avisos'&&user.rol==='ADMIN')await showPushStatus();}catch(e){if([401,403].includes(e.status)){await signOut(auth);location.replace('/login.html');}else showError(e);}finally{polling=false;}}
ready().then(async u=>{if(!u){location.replace('/login.html');return;}const result=await api('me');user=result.usuario;if(!['ADMIN','CLIENTE'].includes(user.rol)){location.replace('/login.html');return;}$('identity').textContent=user.rol+' · '+(user.email||'');for(const n of document.querySelectorAll('[data-admin]'))n.hidden=user.rol!=='ADMIN';$('app').hidden=false;await filters();await loadHistory(true);await avisos();if(await isSupported())onMessage(getMessaging(app),()=>avisos().catch(showError));setInterval(poll,30000);poll();}).catch(showError);
