import {mountNovelty} from './novelty.js';
import {signInWithEmailAndPassword,updatePassword} from 'firebase/auth';
import {$,account,call,notice,showError,busy,install,signOut,line,clear,button,fecha,el} from './common.js';
import {drafts,deleteDraft} from './drafts.js';
const {auth,ready}=account(true);let ronda=null,scanner=null,sending=false;install();
async function refresh(){const data=await call(auth,'activa');ronda=data.ronda;const card=$('active');clear(card);if(ronda){line(card,'Ronda:',ronda.tipoRonda);line(card,'Agente:',ronda.agenteNombre);line(card,'Inicio:',fecha(ronda.inicioTimestamp));line(card,'Validados:',`${ronda.totalValidados} / ${ronda.ruta.length}`);line(card,'Siguiente:',ronda.ruta[ronda.totalValidados]?.nombre);card.append(button('Cancelar ronda',async b=>{const motivo=prompt('Motivo de cancelación:');if(!motivo?.trim())return;if(!confirm('Se cerrará como INCOMPLETA. ¿Continuar?'))return;await busy(b,async()=>{await call(auth,'cancelar',{rondaId:ronda.id,motivo});await refresh();notice('Ronda cancelada.');});},'danger'));}else card.append(el('p','Escanea el QR de INICIO para comenzar tu ronda.'));await showDrafts();}
async function showDrafts(){const list=$('drafts');clear(list);const pending=await drafts(auth.currentUser.uid);for(const d of pending){const card=el('div','','draft');line(card,'Foto pendiente:',d.nombre+' · '+new Date(d.creado).toLocaleString('es-PE'));card.append(button('Reintentar guardado',async b=>busy(b,async()=>{await call(auth,'registrar',d.payload);await deleteDraft(d.key);await refresh();notice('Foto y punto guardados.');})),button('Descartar borrador',async()=>{if(confirm('¿Descartar la fotografía pendiente de este dispositivo?')){await deleteDraft(d.key);await showDrafts();}}));list.append(card);}}
async function stop(){if(scanner){try{await scanner.stop();await scanner.clear();}catch{}scanner=null;}$('stop').hidden=true;$('scan').disabled=false;}
async function startScan(){if(scanner)return;$('scan').disabled=true;try{const {Html5Qrcode}=await import('html5-qrcode');scanner=new Html5Qrcode('reader');await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:250,height:250}},async text=>{if(sending)return;try{const url=new URL(text);if(url.origin!==location.origin||url.pathname!=='/ronda.html')throw Error('Este QR no pertenece a este sistema.');const p=url.searchParams.get('punto')?.toUpperCase();if(!/^P\d{1,12}$/.test(p||''))throw Error('Código no válido.');sending=true;await stop();location.href='/ronda.html?punto='+encodeURIComponent(p);}catch(e){showError(e);sending=false;}},()=>{});$('stop').hidden=false;}catch(e){await stop();throw Error('No se pudo abrir la cámara. Revisa sus permisos. '+e.message);}}
$('login').addEventListener('submit',e=>{e.preventDefault();busy($('submit'),async()=>{const codigo=$('code').value.trim().padStart(3,'0');if(!/^\d{3,6}$/.test(codigo))throw Error('Código inválido.');await signInWithEmailAndPassword(auth,codigo+'@agentes.rondas.invalid',$('password').value);await boot();});});
$('scan').onclick=()=>startScan().catch(showError);$('stop').onclick=stop;
$('logout').onclick=async()=>{if((await drafts(auth.currentUser.uid)).length&&!confirm('Hay fotografías pendientes en este dispositivo. Solo podrás enviarlas al volver a ingresar con esta misma cuenta. ¿Salir?'))return;await stop();await signOut(auth);location.reload();};
$('changePassword').onclick=async()=>{const p=prompt('Nueva contraseña (mínimo 12 caracteres):');if(!p)return;try{if(p.length<12)throw Error('Usa al menos 12 caracteres.');await updatePassword(auth.currentUser,p);notice('Contraseña actualizada.');}catch(e){showError(Error(e.code==='auth/requires-recent-login'?'Vuelve a iniciar sesión y repite el cambio.':e.message));}};
$('refresh').onclick=()=>refresh().catch(showError);
async function boot(){if(!auth.currentUser)return;if(!navigator.onLine){$('loginBox').hidden=true;$('work').hidden=false;$('scan').disabled=true;await showDrafts();notice('Sin conexión. Tus fotos pendientes están guardadas aquí; podrás enviarlas al reconectar.');return;}$('scan').disabled=false;const {usuario}=await call(auth,'me');if(usuario.rol!=='AGENTE'){await signOut(auth);throw Error('Ingresa con una cuenta de agente.');}$('loginBox').hidden=true;$('work').hidden=false;$('identity').textContent='Agente '+usuario.agenteId;const returnPoint=sessionStorage.getItem('returnPoint');if(returnPoint&&/^P\d{1,12}$/.test(returnPoint)){sessionStorage.removeItem('returnPoint');location.replace('/ronda.html?punto='+encodeURIComponent(returnPoint));return;}await refresh();}
ready().then(u=>u&&boot()).catch(showError);addEventListener('online',()=>auth.currentUser&&boot().catch(showError));addEventListener('pagehide',stop);

mountNovelty(auth,{beforeOpen:stop});
