const {chromium}=require('playwright'),{spawn}=require('node:child_process'),fs=require('node:fs'),assert=require('node:assert/strict');
process.env.FIREBASE_PROJECT_ID='demo-rondas';
const {services}=require('../lib/firebase.cjs');const {db,auth,Timestamp}=services();
(async()=>{
 fs.mkdirSync('test-results',{recursive:true});
 await fetch('http://127.0.0.1:8080/emulator/v1/projects/demo-rondas/databases/(default)/documents',{method:'DELETE'});
 for(const [uid,email,rol,agenteId]of [['admin','admin@test.invalid','ADMIN'],['client','client@test.invalid','CLIENTE'],['agente_001','001@agentes.rondas.invalid','AGENTE','001']]){
  try{await auth.createUser({uid,email,password:'Test-Password-12345'});}catch{await auth.updateUser(uid,{email,password:'Test-Password-12345',disabled:false});}
  await db.doc('usuarios/'+uid).set({rol,activo:true,correo:email,...(agenteId?{agenteId}:{})});
  if(agenteId)await db.doc('agentes/'+agenteId).set({uid,codigo:agenteId,nombre:'Agente de prueba',cargo:'Vigilante',turno:'Día',activo:true});
 }
 for(const [i,f]of [[1,'INICIO'],[2,'PUNTO'],[3,'FINAL']])await db.doc('puntos/P0'+i).set({codigo:'P0'+i,nombre:'Punto '+i,direccion:'Av. de prueba 123, Lima',orden:i,funcionQR:f,tipoRonda:'EXTERNA',activo:true});
 const server=spawn(process.execPath,['scripts/dev.cjs'],{env:{...process.env,PORT:'4173'},stdio:'pipe'});let browser;
 try{
  for(let i=0;i<60;i++){try{if((await fetch('http://localhost:4173')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  browser=await chromium.launch({headless:true,args:['--no-sandbox']});const ctx=await browser.newContext({viewport:{width:1360,height:960},serviceWorkers:'block'});const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://localhost:4173/login.html?emulator=1');await page.fill('#email','admin@test.invalid');await page.fill('#password','Test-Password-12345');await page.click('#submit');await page.waitForSelector('#app:not([hidden])');
  await page.click('[data-tab=agentes]');await page.waitForSelector('#agents .card');await page.fill('#agentForm [name=codigo]','003');await page.fill('#agentForm [name=nombre]','Nuevo agente');await page.fill('#agentForm [name=cargo]','Prevención');await page.click('#saveAgent');await page.waitForFunction(()=>document.querySelector('#agents').textContent.includes('003'));
  const card=page.locator('#agents .card').filter({hasText:'003 · Nuevo agente'});await card.getByRole('button',{name:'Crear acceso',exact:true}).click();await page.waitForSelector('dialog');assert((await page.locator('dialog').innerText()).includes('Contraseña temporal'));await page.locator('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();assert.equal((await db.doc('usuarios/agente_003').get()).data().rol,'AGENTE');
  await page.click('[data-tab=puntos]');await page.waitForSelector('#points .card');await page.locator('#points .card').first().getByRole('button',{name:'Ver / descargar QR'}).click();await page.waitForSelector('dialog canvas');await page.waitForFunction(()=>document.querySelector('dialog canvas').width===320);
  fs.writeFileSync('test-results/qr.png',Buffer.from((await page.locator('dialog canvas').evaluate(c=>c.toDataURL())).split(',')[1],'base64'));const qrPixels=await page.locator('dialog canvas').evaluate(c=>({data:Array.from(c.getContext('2d').getImageData(0,0,c.width,c.height).data),width:c.width,height:c.height}));const decoded=require('jsqr')(new Uint8ClampedArray(qrPixels.data),qrPixels.width,qrPixels.height);assert.equal(decoded?.data,'http://localhost:4173/ronda.html?punto=P01');await page.locator('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();
  await page.screenshot({path:'test-results/admin-desktop.png',fullPage:true});
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:1,serviceWorkers:'block'});const agent=await mobile.newPage();agent.on('pageerror',e=>errors.push(e.message));
  await agent.goto('http://localhost:4173/index.html?emulator=1');await agent.fill('#code','001');await agent.fill('#password','Test-Password-12345');await agent.click('#submit');await agent.waitForSelector('#work:not([hidden])');
  await agent.goto('http://localhost:4173/ronda.html?punto=P01');await agent.waitForSelector('#continue:not([disabled])');await agent.click('#continue');await agent.waitForURL('**/camara.html?*');await agent.waitForSelector('#photo:not([disabled])');
  await agent.setInputFiles('#photo','tests/fixtures/evidencia.jpg');await agent.waitForSelector('#save:not([hidden])');await mobile.setOffline(true);await agent.click('#save');await agent.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Sin conexión'));await mobile.setOffline(false);await agent.click('#save');await agent.waitForSelector('#next:not([hidden])');
  await agent.screenshot({path:'test-results/agente-mobile.png',fullPage:true});await agent.reload();await agent.waitForSelector('#share:not([hidden])');await agent.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:()=>Promise.reject(new DOMException('Cancelado','AbortError'))});});await agent.click('#share');assert(await agent.locator('#next').isVisible());
  await agent.goto('http://localhost:4173/ronda.html?punto=P03');await agent.waitForFunction(()=>document.querySelector('#notice').textContent.includes('fuera de secuencia'));assert(await agent.locator('#continue').isDisabled());
  for(const p of ['P02','P03']){await agent.goto('http://localhost:4173/ronda.html?punto='+p);await agent.waitForSelector('#continue:not([disabled])');await agent.click('#continue');await agent.waitForURL('**/camara.html?*');await agent.waitForSelector('#photo:not([disabled])');await agent.setInputFiles('#photo','tests/fixtures/evidencia.jpg');await agent.waitForSelector('#save:not([hidden])');await agent.click('#save');await agent.waitForSelector('#next:not([hidden])');}
  assert((await agent.locator('#next').innerText()).includes('completada'));const rounds=await db.collection('rondas').get();assert.equal(rounds.size,1);assert.equal(rounds.docs[0].data().totalValidados,3);
  await page.click('[data-tab=rondas]');await page.waitForSelector('#rounds .card');await page.locator('#rounds .card').first().getByRole('button',{name:'Ver detalle',exact:true}).click();await page.waitForSelector('.validation');await page.getByRole('button',{name:'Ver fotografía',exact:true}).first().click();await page.waitForSelector('dialog img');assert((await page.locator('dialog img').getAttribute('src')).startsWith('data:image/jpeg;base64,'));await page.locator('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();await page.screenshot({path:'test-results/historial-desktop.png',fullPage:true});
  // Datos no confiables deben aparecer como texto, nunca convertirse en etiquetas.
  await db.collection('eventosPush').add({tipoEvento:'INICIO',agenteNombre:'<img src=x onerror="window.xss=1">',tipoRonda:'EXTERNA',creadoEn:Timestamp.now(),estado:'ENVIADO'});
  await page.click('[data-tab=avisos]');await page.waitForFunction(()=>document.querySelector('#notifications').textContent.includes('<img'));assert.equal(await page.locator('#notifications img').count(),0);assert.equal(await page.evaluate(()=>window.xss),undefined);
  const clientctx=await browser.newContext({serviceWorkers:'block'});const client=await clientctx.newPage();await client.goto('http://localhost:4173/login.html?emulator=1');await client.fill('#email','client@test.invalid');await client.fill('#password','Test-Password-12345');await client.click('#submit');await client.waitForSelector('#app:not([hidden])');assert(await client.locator('[data-tab=agentes]').isHidden());assert(await client.locator('[data-tab=usuarios]').isHidden());assert.equal(await client.getByRole('button',{name:'Archivar',exact:true}).count(),0);
  const workerctx=await browser.newContext();const workerpage=await workerctx.newPage();await workerpage.goto('http://localhost:4173/index.html?emulator=1');await workerpage.evaluate(()=>navigator.serviceWorker.ready);await workerpage.reload();await workerctx.setOffline(true);await workerpage.goto('http://localhost:4173/index.html');await workerpage.waitForSelector('#loginBox');await workerctx.close();
  const overflow=await agent.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,'La pantalla móvil no debe desbordarse horizontalmente.');assert.deepEqual(errors,[]);
  console.log('NAVEGADOR OK: login ADMIN/CLIENTE/AGENTE, crear acceso, QR, recorrido completo, orden, borrador offline/reintento, foto en historial, texto anti-XSS y pantalla móvil.');
 }finally{if(browser)await browser.close();server.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exit(1);});
